name: Bug 报告 / 问题反馈
description: 报告使用过程中遇到的问题
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您花时间填写此问题报告！在提交之前，请确保您已完成以下检查。

  - type: markdown
    attributes:
      value: |
        ### 1. 问题检查清单

  - type: checkboxes
    id: checklist
    attributes:
      label: 必填检查项
      description: 在提交 issue 之前，请确认您已完成以下检查
      options:
        - label: 我已经搜索过 [现有的 Issues](https://github.com/zpj80231/idea-set/issues?q=is%3Aissue)，没有找到类似问题
          required: true
        - label: 我已经仔细阅读了 [README.md](https://github.com/zpj80231/idea-set/blob/master/README.md) 文档
          required: true
        - label: 当前仓库是否为最新代码（请更新至最新版本重试）
          required: true
  
  - type: markdown
    attributes:
      value: |
        ### 2. 环境信息
  
  - type: input
    id: os-version
    attributes:
      label: 2.1 操作系统
      description: 如果是 macOS，请填写版本号（如 14.1）；如果是 Linux，请填写发行版名称
      placeholder: 例如：macOS 15.7.1 或 Windows 11
    validations:
      required: true
  
  - type: input
    id: jetbrains-product
    attributes:
      label: 2.2 JetBrains 产品信息
      description: 请填写产品名称和完整版本号
      placeholder: 例如：IntelliJ IDEA 2025.2.5 或 PyCharm 2024.2
    validations:
      required: true
  
  - type: markdown
    attributes:
      value: |
        ### 3. 问题描述
  
  - type: textarea
    id: problem-description
    attributes:
      label: 3.1 简要描述
      description: 请简明扼要地描述遇到的问题
      placeholder: 描述您遇到的问题...
    validations:
      required: true
  
  - type: textarea
    id: reproduction-steps
    attributes:
      label: 3.2 重现步骤
      description: 请详细描述如何重现这个问题，包括每一步操作
      placeholder: |
        1. 首先...
        2. 然后...
        3. 接着...
        4. 最后...
    validations:
      required: true
  
  - type: textarea
    id: expected-behavior
    attributes:
      label: 预期行为
      description: 描述您期望发生什么
      placeholder: 我期望...
    validations:
      required: true
  
  - type: textarea
    id: actual-behavior
    attributes:
      label: 实际行为
      description: 描述实际发生了什么
      placeholder: 实际上...
    validations:
      required: true
  
  - type: markdown
    attributes:
      value: |
        ### 4. 相关信息
  
  - type: textarea
    id: config-file
    attributes:
      label: 4.1 配置文件内容
      description: 如果问题与配置相关，请粘贴您的 .vmoptions 文件内容（去除敏感信息）
      placeholder: |
        # 配置文件名称及全路径
        
        # 配置内容
      render: properties
    validations:
      required: false
  
  - type: textarea
    id: screenshots
    attributes:
      label: 4.2 截图
      description: 如果适用，请拖拽或粘贴截图来帮助说明问题
      placeholder: 可以直接粘贴截图到这里
    validations:
      required: false
  
  - type: markdown
    attributes:
      value: |
        ### 5. 补充信息
  
  - type: textarea
    id: tried-solutions
    attributes:
      label: 5.1 已尝试的解决方案
      description: 请描述您已经尝试过哪些解决方案
      placeholder: |
        - 尝试了...
        - 还尝试了...
    validations:
      required: false
  
  - type: textarea
    id: additional-info
    attributes:
      label: 5.2 其他说明
      description: 任何其他可能有助于解决问题的信息
    validations:
      required: false
  
  - type: textarea
    id: error-logs
    attributes:
      label: 5.3 错误日志
      description: 如果有错误日志，请粘贴相关内容。日志位置：Help -> Show Log in Finder/Explorer
      placeholder: 请粘贴错误日志...
      render: shell
    validations:
      required: false

